services:

  pro-notes-api:
    image: pro-notes-api:latest
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    restart: "no"
    env_file:
      - .env
    ports:
      - "${API_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:$PORT/ || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      - pro-notes-postgres

  pro-notes-postgres:
    image: postgres:17.0
    restart: "no"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pro-notes-postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

volumes:
  pro-notes-postgres_data:
