server:
  port: ${API_PORT}

spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=public
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
