spring:
  application:
    name: pro-notes-api
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

springdoc:
  override-with-generic-response: false

custom:
  security:
    jwt:
      secret: ${JWT_SECRET}
      access: ${JWT_ACCESS}
      refresh: ${JWT_REFRESH}
  integrations:
    giga-chat:
      xClientId: ${GIGA_CHAT_X_CLIENT_ID}
      authorizationToken: ${GIGA_CHAT_API_AUTHORIZATION_TOKEN}
